### ISSUE TITLE
"Error on retrieving server data from provider"?

### ISSUE THREAD

**Issue by someonedeepintheinternet** [enjarai/OmniHopper#14] opened 2023-08-24 15:07 UTC
Hi, I found this nice mod and downloaded it but when I joined my world, I immediately received this message in the chat which concerns me on upcoming crashings:

Error on retrieving server data from provider
mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider$$Lambda$15031/0x0000000801cf8000

**Comment by enjarai** [comment] 2023-08-24 15:14
I can try to find the cause if you send a full log that includes this error. It's probably harmless though, so I wouldn't worry about it.

**Comment by someonedeepintheinternet** [comment] 2023-08-24 15:59
where do I find the log? it has not crashed so its not in the crash report

**Comment by deirn** [comment] 2023-08-27 14:16
The issue is on here https://github.com/enjarai/OmniHopper/blob/60287556c8efce8db89ef945c3a06f663f49e7e0/src/main/java/nl/enjarai/omnihopper/mixin/AbstractFurnaceBlockEntityMixin.java#L37-L42

On 1.20, FAPI's `ItemStorage.SIDED` and `FluidStorage.SIDED` allows for null side. The method on `SidedStorageBlockEntity` is not marked as such though (it's an oversight).

https://github.com/FabricMC/fabric/pull/3281
https://github.com/badasintended/wthit/issues/231

**Comment by enjarai** [comment] 2023-08-27 15:17
Oh I see, thanks for letting me know! I'll push an update to implement a null check.

**Comment by someonedeepintheinternet** [comment] 2023-08-28 13:42
oh well, guess I don't have to explain further

**Closed as completed** 2023-08-28 13:43 UTC
